# 02 - A Layer of Neurons, with PyTorch

Building on `01_single_neuron.py`, where we wrote a single neuron (weighted sum + bias + activation) by hand with plain loops.

Here, we do the same thing using PyTorch:

- `nn.Linear(in_features=2, out_features=3)` creates a **layer of 3 neurons**, each expecting 2 inputs — this replaces our manual loop entirely
- We overwrote its randomly-initialized weights/bias with the exact values from our by-hand example, to confirm PyTorch gives the same answer
- `layer(inputs)` runs the **forward pass** — the same weighted-sum-plus-bias math, for all 3 neurons at once
- `torch.relu(...)` replaces our hand-written `relu` function

**Result:** PyTorch produced the exact same output as our by-hand calculation — `[0.5, 1.5, 1.0]` — confirming it's doing the same math, just faster, and with `requires_grad=True` tracking everything automatically for backpropagation later.

**Next up:** the loss function — measuring how "wrong" a network's output is.

In [ ]:
import torch 
import torch.nn as nn

In [12]:
layer = nn.Linear(in_features=2, out_features=3)
print(layer.weight)
print(layer.bias)

Parameter containing:
tensor([[ 0.2861, -0.2150],
        [ 0.5802,  0.3882],
        [-0.5521, -0.3108]], requires_grad=True)
Parameter containing:
tensor([-0.5299, -0.4512,  0.2509], requires_grad=True)


In [13]:
with torch.no_grad():
    layer.weight.copy_(torch.tensor([
        [0.5, -0.5],
        [0.2, 0.8],
        [-1.0, 1.0]
    ]))
    layer.bias.copy_(torch.tensor([1.0, -0.3, 0.0]))

print(layer.weight)
print(layer.bias)

Parameter containing:
tensor([[ 0.5000, -0.5000],
        [ 0.2000,  0.8000],
        [-1.0000,  1.0000]], requires_grad=True)
Parameter containing:
tensor([ 1.0000, -0.3000,  0.0000], requires_grad=True)


In [14]:
inputs = torch.tensor([1.0, 2.0])

raw_output = layer(inputs)
print(raw_output)

tensor([0.5000, 1.5000, 1.0000], grad_fn=<ViewBackward0>)


In [15]:
activated_output = torch.relu(raw_output)
print(activated_output)

tensor([0.5000, 1.5000, 1.0000], grad_fn=<ReluBackward0>)
